### PR TITLE
fix Clang-CUDA math tests

### LINKED ISSUE #1020: math test failed with Clang as CUDA compiler
```bash
cmake -DBoost_USE_STATIC_LIBS=ON -DBoost_USE_MULTITHREADED=ON -DBoost_USE_STATIC_RUNTIME=OFF -DCMAKE_BUILD_TYPE=Release -DALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLE=ON -DALPAKA_ACC_CPU_B_SEQ_T_THREADS_ENABLE=OFF -DALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE=OFF -DALPAKA_ACC_CPU_B_TBB_T_SEQ_ENABLE=OFF -DALPAKA_ACC_CPU_B_OMP2_T_SEQ_ENABLE=OFF -DALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLE=OFF -DALPAKA_ACC_CPU_BT_OMP4_ENABLE=OFF -DALPAKA_ACC_GPU_CUDA_ENABLE=ON -DALPAKA_ACC_GPU_HIP_ENABLE=OFF -DALPAKA_DEBUG=0 -DALPAKA_CUDA_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -Dalpaka_BUILD_EXAMPLES=ON -DBUILD_TESTING=ON ..
```

```bash
build/test/unit/math/math
using seed: 1337

testing:
 3 - accelerators !
17 - unary math operators
6 - binary math operators
testing with two data types
total 2 * accelerators * (unary + binary) * capacity


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
math is a Catch v2.11.0 host application.
Run with -? for options

-------------------------------------------------------------------------------
mathOps
-------------------------------------------------------------------------------
/alpaka/test/unit/math/src/math.cpp:173
...............................................................................

/alpaka/test/unit/math/src/math.cpp:144: FAILED:
  REQUIRE( results(i) == Approx(std_result) )
with expansion:
  -inf == Approx( inf )
with messages:
  Operator: OpExp
  Type: d
  The args buffer: 
  capacity: 1000
  0: [ 0, ]
  1: [ 1.797693134862316e+308, ]
  2: [ -1.797693134862316e+308, ]
  3: [ -866.0227473557505, ]
  4: [ 215.2263814000266, ]
  5: [ -748.4321206839105, ]
  6: [ 642.1264531942572, ]
  7: [ -684.4018728416871, ]
  8: [ 459.689454949301, ]
  9: [ -222.9117748544045, ]
  10: [ 209.1584889667682, ]
  11: [ -292.4749641267939, ]
  12: [ 368.071562313879, ]
  13: [ -215.1164257009424, ]
  14: [ 993.5934513103955, ]
  15: [ -503.7756326294896, ]
  16: [ 289.652593683621, ]
  17: [ -491.8247722903218, ]
  18: [ 58.77905907878117, ]
  19: [ -460.0548273044462, ]
  20: [ 849.1603358834052, ]
  21: [ -320.8197171238272, ]
  22: [ 457.8027599177277, ]
  23: [ -669.7326682649812, ]
  24: [ 236.7513732381438, ]
  25: [ -181.0255020122907, ]
  26: [ 853.430905473642, ]
  27: [ -482.0493555522171, ]
  28: [ 727.3698115061305, ]
# ...
```

Tested on `fwk394` with `CUDA 10.1`, `Clang 10.0`, `CMake 3.16.5` and `Boost 1.73.0` via `Spack`. It also fails with the Alpaka-CI Docker image (the image is not public available at the moment -> I work on it).

### PR DESCRIPTION
**Pull request by psychocoderHPC**
fix: #1020

The math tests sometimes failed because we using random input data for tests and `exp` results are not exact compared to `std::exp`.

Implement https://github.com/alpaka-group/alpaka/issues/1020#issuecomment-898558123 and allow result differences of one epsilon.

### CODE REVIEW

File: test/unit/math/src/math.cpp [hunk 1]
```diff
@@ -125,7 +125,7 @@ struct TestTemplate
         {
             INFO("Idx i: " << i)
             TData std_result = functor(args(i));
-            REQUIRE(results(i) == Approx(std_result));
+            REQUIRE(results(i) == Approx(std_result).margin(std::numeric_limits<TData>::epsilon()));
```
Comment (bernhardmgruber) [inline test/unit/math/src/math.cpp:128]: I was first confused by this, since `Approx` already sets an epsilon of `std::numeric_limits<float>::epsilon()*100`. But then I saw you set a margin, which by default is 0, instead of an epsilon.

**Review by bernhardmgruber — APPROVED** [review]
