### PR TITLE
fix callback thread task lifetime

### LINKED ISSUE #1936: `eventTest` has a race condition
The `eventTest` in alpaka has a race condition that spurriously occurs in the CI. TSAN finds it as well:
```
==================
WARNING: ThreadSanitizer: data race (pid=68572)
  Write of size 8 at 0x7b4400000490 by main thread:
    #0 operator delete(void*, unsigned long) ../../../../src/libsanitizer/tsan/tsan_new_delete.cpp:150 (libtsan.so.2+0x8cd75)
    #1 std::_Function_handler<void (), alpaka::generic::detail::QueueGenericThreadsNonBlockingImpl<alpaka::DevCpu>::~QueueGenericThreadsNonBlockingImpl()::{lambda()#1}>::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation) <null> (eventTest+0x344a5)

  Previous atomic read of size 1 at 0x7b4400000490 by thread T1:
    #0 pthread_mutex_lock ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:4324 (libtsan.so.2+0x59bcf)
    #1 std::_Sp_counted_ptr_inplace<alpaka::core::detail::ConcurrentExecPool<unsigned long, std::thread, std::promise, void, std::mutex, std::condition_variable, false>, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() <null> (eventTest+0x32e9d)

  Thread T1 (tid=68574, finished) created by main thread at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1001 (libtsan.so.2+0x63a69)
    #1 std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) <null> (libstdc++.so.6+0xdc478)
    #2 Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) <null> (eventTest+0x89062)
    #3 Catch::RunContext::runTest(Catch::TestCaseHandle const&) <null> (eventTest+0x8963e)
    #4 Catch::Session::runInternal() <null> (eventTest+0x4450b)
    #5 Catch::Session::run() <null> (eventTest+0x44ea6)
    #6 main <null> (eventTest+0x277b9)

SUMMARY: ThreadSanitizer: data race ../../../../src/libsanitizer/tsan/tsan_new_delete.cpp:150 in operator delete(void*, unsigned long)
==================
```
The usual suspects again, `ConcurrentExecPool` and `QueueGenericThreadsNonBlockingImpl`. May be related to the queue bug #1741.

### LINKED ISSUE #2007: `queueTest` has a race condition.
Under random circumstances `queueTest` will fail with the following error message:

```
38: /home/runner/work/alpaka/alpaka/test/unit/queue/src/QueueTest.cpp:101: FAILED:
38:   CHECK( alpaka::empty(f.m_queue) )
38: with expansion:
38:   false
```

Example: https://github.com/alpaka-group/alpaka/actions/runs/5620806464/job/15230414419?pr=2006#step:5:7252

This is probably related to #1741 and #1936.

### PR DESCRIPTION
**Pull request by psychocoderHPC**
fix:  https://github.com/alpaka-group/alpaka/issues/2007 

Rewrite the callback thread to have a well-defined lifetime of the enqueued tasks and the moment when the future will be set after the tasks are executed.
The lifetime issue of data captured by a lambda introduced with https://github.com/alpaka-group/alpaka/pull/1870
is solved too and explicit destroying data is not required anymore.

- [x] depends on #2022

### CODE REVIEW

File: include/alpaka/core/CallbackThread.hpp [hunk 1]
```diff
@@ -61,8 +61,9 @@ namespace alpaka::core
                 m_tasks.emplace(std::move(task));
                 if(!m_thread.joinable())
                     startWorkerThread();
+                m_cond.notify_one();
             }
-            m_cond.notify_one();
+
```
Comment (bernhardmgruber) [inline include/alpaka/core/CallbackThread.hpp]: Is that a necessary change? AFAIK notifying a condition variable outside the lock is actually the preferred implementation, since the notified thread can immediately acquire the lock.

File: test/unit/queue/src/QueueTest.cpp [hunk 2]
```diff
@@ -76,15 +76,18 @@ TEMPLATE_LIST_TEST_CASE(
     Fixture f;
 
     std::atomic<bool> callbackFinished{false};
+    std::atomic<bool> inKernelIsNotEmptyBeforeSleep{false};
+    std::atomic<bool> inKernelIsNotEmptyAfterSleep{false};
+
     alpaka::enqueue(
         f.m_queue,
-        [&f, &callbackFinished]() noexcept
+        [&f, &callbackFinished, &inKernelIsNotEmptyBeforeSleep, &inKernelIsNotEmptyAfterSleep]() noexcept
```
Comment (bernhardmgruber) [inline test/unit/queue/src/QueueTest.cpp]:
```suggestion
        [&]() noexcept
```
I think I would just capture all now. Applies to the other lambdas as well.

**Comment by j-stephan** [comment]
Still failing :-(

File: include/alpaka/core/CallbackThread.hpp (hunk 1 above)
Comment (psychocoderHPC) [reply include/alpaka/core/CallbackThread.hpp]: Yes it is the same as in the de-structor we can miss the notification. The sanitizer issues got solved by this line.

**Comment by psychocoderHPC** [comment]
> Still failing :-(

Most likely the test is failing in `alpaka/test/unit/queue/src/CollectiveQueue.cpp`. I am currently checking whats going on there.
The test is providing a special queue DLR is using.

File: test/unit/queue/src/QueueTest.cpp (hunk 2 above)
Comment (psychocoderHPC) [reply test/unit/queue/src/QueueTest.cpp]: I also thought about it but since we where explicit before I kept it.

File: include/alpaka/core/CallbackThread.hpp (hunk 1 above)
Comment (bernhardmgruber) [reply include/alpaka/core/CallbackThread.hpp]: Ah, I remember.  Alright then!

**Comment by psychocoderHPC** [comment]
@bernhardmgruber @j-stephan 

I added a bunch of commits to this fix. The reason why I have not separated the fixes into different PR's is that all are related to the queue tests that we rely on a thread-safe implementation of the callback thread.

With all these fixes I do not see any more issues in the sanitizer.

**Comment by psychocoderHPC** [comment]
Current CI issue:

```
38: enqueueBenchmark - alpaka::test::TestQueues - 1
38: -------------------------------------------------------------------------------
38: /home/runner/work/alpaka/alpaka/test/unit/queue/src/QueueTest.cpp:198
38: ...............................................................................
38: 
38: terminating with uncaught exception of type std::__1::future_error: The state of the promise has already been set.
38: benchmark name                       samples       iterations    estimated
38:                                      mean          low mean      high mean
38:                                      std dev       low std dev   high std dev
```

File: test/unit/queue/src/QueueTest.cpp (hunk 2 above)
Comment (psychocoderHPC) [reply test/unit/queue/src/QueueTest.cpp]: done

**Comment by psychocoderHPC** [comment]
Successfully passed all tests once, I will force push again to check if it is a false positive.

**Comment by bernhardmgruber** [comment]
This PR is starting to touch too many things. And I also don't believe all changes here are necessary, but it's harder to argue the bigger the PR gets. Can you please split off:
* the changes avoiding multithreaded use of Catch2
* the bugfix for resetting the event shared pointers while mutexes are being held.

Thx a lot!

**Comment by psychocoderHPC** [comment]
> This PR is starting to touch too many things. And I also don't believe all changes here are necessary, but it's harder to argue the bigger the PR gets. Can you please split off:
> 
> * the changes avoiding multithreaded use of Catch2
> * the bugfix for resetting the event shared pointers while mutexes are being held.
> 
> Thx a lot!

I created #2023 and #2022 to pull out two fixes in the tests.
Changes in `CallbackThread.hpp` should not be split, I will reduce the number of commits with the rebase after both dependency PRs are merged.

File: include/alpaka/core/CallbackThread.hpp [hunk 3]
```diff
@@ -38,11 +40,8 @@ namespace alpaka::core
             }
         }
 
-        // Note: due to different std lib implementations of packaged_task, the lifetime of the passed function either
-        // ends when the packaged_task is destroyed (while the returned future is still alive) or when both are
-        // destroyed. Therefore, ensure that a submitted task does not extend the lifetime of any object that
-        // (transitively) holds the returned future. E.g. don't capture a shared_ptr to an alpaka object that stores
-        // the returned future. This is a cyclic dependency and creates a leak.
+        //! It is guaranteed that the task is fully destroyed before future result is set.
```
Comment (bernhardmgruber) [inline include/alpaka/core/CallbackThread.hpp]:
```suggestion
        //! It is guaranteed that the task is fully destroyed before the future's result is set.
```

File: include/alpaka/core/CallbackThread.hpp [hunk 4]
```diff
@@ -16,7 +16,9 @@ namespace alpaka::core
 {
     class CallbackThread
     {
+        // std::packaged_task is used because std::function requires that the wrapped callable is copyable.
```
Comment (bernhardmgruber) [inline include/alpaka/core/CallbackThread.hpp:19]: You can add a comment to replace it by `std::move_only_function` in C++23 :)

File: include/alpaka/core/CallbackThread.hpp [hunk 5]
```diff
@@ -54,30 +53,35 @@ namespace alpaka::core
 
         auto submit(Task task) -> std::future<void>
         {
-            auto f = task.get_future();
+            auto tp = std::make_pair(std::move(task), std::promise<void>{});
```
Comment (bernhardmgruber) [inline include/alpaka/core/CallbackThread.hpp:59]: Please add a comment here that we do NOT use the `packaged_task`'s future, because it keeps the task alive.

File: include/alpaka/event/EventGenericThreads.hpp [hunk 6]
```diff
@@ -147,15 +147,16 @@ namespace alpaka
                 spEventImpl->m_future = queueImpl.m_workerThread.submit(
                     [spEventImpl, enqueueCount]() mutable
                     {
-                        std::unique_lock<std::mutex> lk2(spEventImpl->m_mutex);
-
-                        // Nothing to do if it has been re-enqueued to a later position in the queue.
-                        if(enqueueCount == spEventImpl->m_enqueueCount)
+                        // The lock is released before the shared pointer is reset.
```
Comment (bernhardmgruber) [inline include/alpaka/event/EventGenericThreads.hpp]: We don't need that comment anymore, do we?

File: include/alpaka/event/EventGenericThreads.hpp [hunk 7]
```diff
@@ -302,10 +303,11 @@ namespace alpaka
...
                         {
-                            std::unique_lock<std::mutex> lk2(spEventImpl->m_mutex);
-                            spEventImpl->wait(enqueueCount, lk2);
-                            spEventImpl.reset(); // avoid keeping the event alive as part of the background thread
-                                                 // task's future
+                            {
+                                // The lock is released before the shared pointer is reset.
+                                std::unique_lock<std::mutex> lk2(spEventImpl->m_mutex);
+                                spEventImpl->wait(enqueueCount, lk2);
+                            }
```
Comment (bernhardmgruber) [inline include/alpaka/event/EventGenericThreads.hpp]:
```suggestion
                                std::unique_lock<std::mutex> lk2(spEventImpl->m_mutex);
                                spEventImpl->wait(enqueueCount, lk2);
```

File: include/alpaka/queue/cuda_hip/QueueUniformCudaHipRt.hpp [hunk 8]
```diff
@@ -203,12 +203,7 @@ namespace alpaka
             {
                 auto data = std::unique_ptr<HostFuncData>(reinterpret_cast<HostFuncData*>(arg));
                 auto& queue = data->q;
-                auto f = queue.m_callbackThread.submit(
-                    [data = std::move(data)]() mutable
-                    {
-                        data->t();
-                        data.reset(); // destroy the task
-                    });
+                auto f = queue.m_callbackThread.submit([data = std::move(data)]() mutable { data->t(); });
```
Comment (bernhardmgruber) [inline include/alpaka/queue/cuda_hip/QueueUniformCudaHipRt.hpp]:
```suggestion
                auto f = queue.m_callbackThread.submit([data = std::move(data)] { data->t(); });
```

File: include/alpaka/test/event/EventHostManualTrigger.hpp [hunk 9]
```diff
@@ -180,13 +180,14 @@ namespace alpaka::trait
...
-                    spEventImpl
-                        .reset(); // avoid keeping the event alive as part of the background thread task's future
+                    {
+                        // The lock is released before the shared pointer is reset.
+                        std::unique_lock<std::mutex> lk2(spEventImpl->m_mutex);
+                        spEventImpl->m_conditionVariable.wait(
+                            lk2,
+                            [spEventImpl, enqueueCount]
+                            { return (enqueueCount != spEventImpl->m_enqueueCount) || spEventImpl->m_bIsReady; });
+                    }
```
Comment (bernhardmgruber) [inline include/alpaka/test/event/EventHostManualTrigger.hpp]:
```suggestion
                        std::unique_lock<std::mutex> lk2(spEventImpl->m_mutex);
                        spEventImpl->m_conditionVariable.wait(
                            lk2,
                            [spEventImpl, enqueueCount]
                            { return (enqueueCount != spEventImpl->m_enqueueCount) || spEventImpl->m_bIsReady; });
```

**Review by bernhardmgruber — DISMISSED** [review]

**Comment by psychocoderHPC** [comment]
@bernhardmgruber Thanks for the review, I change the parts you annotated and a few left over comments.

**Review by j-stephan — APPROVED** [review]
