### PR TITLE
Disable part of the threadpool test for TSAN

### LINKED ISSUE #2101: coreTest fails with TSAN
The clang-16 TSAN CI job failed a few times at the coreTest. See for example [here](https://github.com/alpaka-group/alpaka/actions/runs/5999816286/job/16270849037?pr=2092#step:5:4976).

PR #2103 disabled the offending test. We should revisit this in the future and make the test work.

### PR DESCRIPTION
**Pull request by bernhardmgruber**
Fixes: #2101.

### CODE REVIEW

File: test/unit/core/src/ThreadPool.cpp [hunk 1]
```diff
@@ -16,6 +22,10 @@ TEST_CASE("threadpool", "[core]")
 
     CHECK_THROWS_AS(f1.get(), std::runtime_error);
 
+#ifdef TSAN
+#    warning "Part of the threadpool test fails the TSAN CI and is therefore disabled."
+    // TODO(bgruber): Revisit this in the future on a new CI image. This problem does not happen locally.
```
Comment (j-stephan) [inline test/unit/core/src/ThreadPool.cpp:27]: Interesting. So probably some Ubuntu 20.04 issue then?

**Review by j-stephan — APPROVED** [review]

File: test/unit/core/src/ThreadPool.cpp (hunk 1 above)
Comment (bernhardmgruber) [reply test/unit/core/src/ThreadPool.cpp:27]: I have no idea. It does not happen on my Ubuntu 23.04. Also interestingly, the CI reports a higher `BOOST_LIB_STD_GNU` than my local run :D In any case, all I can do is disable the test and add this note. Let's have a look again on newer Ubuntu images.
