### PR TITLE
Enforce trivially copyable kernel arguments

### LINKED ISSUE #703: Investigate usage of std::is_trivially_copyable
It is meant to check that the kernel can be copied to the GPU with a simple memcpy. However the check fails on all platforms so something might be wrong.

### LINKED ISSUE #1384: kernel parameter should be trivially copy-able
During the CUDA HIP refactoring, important checks were removed

https://github.com/alpaka-group/alpaka/blob/ab0b8a460f398fef7e475892ff5af98f947ce128/include/alpaka/kernel/TaskKernelGpuCudaRt.hpp#L145-L154

These checks are important to check compatibility and must be reintroduced.

### PR DESCRIPTION
**Pull request by j-stephan**
Fixes #1384. This PR enforces all kernel arguments to be trivially copyable.

The check for the kernel function object being trivially copyable is deliberately left out until a consensus on #1634 has been reached.

### CODE REVIEW

File: include/alpaka/kernel/Traits.hpp [hunk 1]
```diff
@@ -222,6 +222,9 @@ namespace alpaka
         // check for void return type
         detail::CheckFnReturnType<TAcc>{}(kernelFnObj, args...);
 
+        static_assert(
+            std::conjunction_v<std::is_trivially_copyable<std::decay_t<TArgs>>...>,
+            "Kernel arguments must be trivially copyable!");
```
Comment (bernhardmgruber) [inline include/alpaka/kernel/Traits.hpp]:
```suggestion
        static_assert(
            (std::is_trivially_copyable_v<std::decay_t<TArgs>> && ... && true),
            "Kernel arguments must be trivially copyable!");
```
I prefer a fold, but up to you!

**Review by bernhardmgruber — DISMISSED** [review]

File: include/alpaka/kernel/Traits.hpp (hunk 1 above)
Comment (j-stephan) [reply include/alpaka/kernel/Traits.hpp]: From what I understand a fold instantiates all parameters while `std::conjunction` will look at them individually (and fail at the first `false`).

Comment (fwyzard) [reply include/alpaka/kernel/Traits.hpp]: By the way, the final `&& true` is not necessary.

Comment (bernhardmgruber) [reply include/alpaka/kernel/Traits.hpp]: Maybe, but it should not matter. Anyway, do what you prefer! :)

Comment (bernhardmgruber) [reply include/alpaka/kernel/Traits.hpp]: > By the way, the final && true is not necessary.

That would not work for kernels without arguments, which are probably rare or even nonsensical. But why prevent it?

Comment (fwyzard) [reply include/alpaka/kernel/Traits.hpp]: Mhm, I think it should work also with an empty argument list: https://godbolt.org/z/TP99M1nfh . 

[Cppreference](https://en.cppreference.com/w/cpp/language/fold#Explanation) says
> When a unary fold is used with a pack expansion of length zero, only the following operators are allowed:
> 1) Logical AND (`&&`). The value for the empty pack is `true`

Comment (fwyzard) [reply include/alpaka/kernel/Traits.hpp]: > From what I understand a fold instantiates all parameters while `std::conjunction` will look at them individually (and fail at the first `false`).

I think the fold expression itself does follow short-circuit evaluation: https://godbolt.org/z/e3jbbh4d3 .
The values after the first `false` are not evaluated.

**Comment by j-stephan** [comment]
Interestingly clang and gcc disagree on what is a `trivially_copyable` type: https://godbolt.org/z/svYv4Ydxx

File: include/alpaka/kernel/Traits.hpp (hunk 1 above)
Comment (j-stephan) [reply include/alpaka/kernel/Traits.hpp]: I was following the info from this link: https://stackoverflow.com/questions/55161235/is-there-a-reason-to-use-stdconjunction-stddisjunction-instead-of-a-fold-exp#comment97065030_55161485

**Comment by fwyzard** [comment]
Interesting...

The do agree on the individual data members (they are all trivially copyable), but not on the aggregate structure 🤔

File: include/alpaka/kernel/Traits.hpp (hunk 1 above)
Comment (j-stephan) [reply include/alpaka/kernel/Traits.hpp]: But anyway, I don't think this will hurt our compilation performance much. And having a language feature instead of a library feature is also nice, so I'll change to a fold expression.

**Comment by fwyzard** [comment]
If I add an explicit default constructor to the example
```c++
struct X
{
    X() = default;
    
    Vec const ext;
    float* ptr;
    std::integral_constant<unsigned long, 1> idx;
};
```

GCC is happy, while clang complains with
```
<source>:9:5: warning: explicitly defaulted default constructor is implicitly deleted [-Wdefaulted-function-deleted]
    X() = default;
    ^
<source>:11:15: note: default constructor of 'X' is implicitly deleted because field 'ext' of const-qualified type 'const Vec' would not be initialized
    Vec const ext;
```

So, clang does not consider `X` to be `trivially_constructible`, while GCC does.

**Comment by j-stephan** [comment]
Yeah... I'll just remove the `const`ness of `IteratorView`'s members, it doesn't serve a purpose anyway.

**Comment by fwyzard** [comment]
There seem to be an open defect report about this since quite some time now: http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#253 .

File: include/alpaka/kernel/Traits.hpp (hunk 1 above)
Comment (fwyzard) [reply include/alpaka/kernel/Traits.hpp]: Ah, I see. Yes, you are right, the arguments are instantiated, even if they are not evaluated: https://godbolt.org/z/osjbc98an .

**Review by bernhardmgruber — APPROVED** [review]
