### PR TITLE
Always use `std::size_t` for CUDA pitch calculations

### LINKED ISSUE #1933: BabelStream error
Running Babelstream with a workingset of 6.4 GB on a V100 with 32GB memory produces the following error:
```
bash-4.2$ make babelstream && ./example/babelstream/babelstream -s 268435456
[100%] Built target babelstream
BabelStream
Version: 4.0
Implementation: alpaka
Running kernels 100 times
Precision: double
Array size: 2147.5 MB (=2.1 GB)
Total size: 6442.5 MB (=6.4 GB)
Using alpaka device Tesla V100-SXM2-32GB
terminate called after throwing an instance of 'std::runtime_error'
  what():  /home/bg143886/alpaka/include/alpaka/mem/buf/uniformCudaHip/Copy.hpp(161) 'TApi::memcpyAsync( m_dstMemNative, m_srcMemNative, static_cast<std::size_t>(m_extentWidthBytes), m_uniformMemCpyKind, queue.getNativeHandle())' returned error  : 'cudaErrorInvalidValue': 'invalid argument'!
Aborted
```
This seems odd, since the allocated memory is far less then what the GPU has available.

### PR DESCRIPTION
**Pull request by j-stephan**
This PR hard-codes buffer and pitch sizes to `std::size_t` as there is no real reason for having other types here. It is also an attempt to fix #1933.

### CODE REVIEW

**Comment by fwyzard** [comment]
In CMSSW we use `Idx = uint32_t`, because I am fairly convinced we do not have any single object even close to 4GB.

Before making this change, I would like to have a stable code base and test if this has any impact.

**Comment by j-stephan** [comment]
Okay, sure. Should this PR hurt your codebase I can also change it to accept general unsigned integer types.

**Comment by bernhardmgruber** [comment]
I think using `std::size_t` in host code should generally be fine. I wonder about the pitch traits tough, since you could call them in device code and pitches (at least for the near future) should fit into a 32bit int :)

> In CMSSW we use Idx = uint32_t, because I am fairly convinced we do not have any single object even close to 4GB.

Great! I hit this limit all the time though, but I do synthetic benchmarks for my PhD, which involves arrays that should fill recent GPUs.

File: include/alpaka/mem/buf/BufUniformCudaHipRt.hpp [hunk 1]
```diff
@@ -41,14 +42,15 @@ namespace alpaka
             "The elem type of the buffer can not be const because the C++ Standard forbids containers of const "
             "elements!");
         static_assert(!std::is_const_v<TIdx>, "The idx type of the buffer can not be const!");
+        static_assert(std::is_unsigned_v<TIdx>, "The idx type of the buffer must be an unsigned arithmetic type!");
```
Comment (bernhardmgruber) [inline include/alpaka/mem/buf/BufUniformCudaHipRt.hpp]: Why is this required?

**Comment by j-stephan** [comment]
This is now ready for review / checking out if it breaks any existing codebases...

**Comment by bernhardmgruber** [comment]
Tried your PR on hemera, looks good:
```
bash-4.2$ make -j10 babelstream && ./example/babelstream/babelstream -s 268435456
[100%] Built target babelstream
BabelStream
Version: 4.0
Implementation: alpaka
Running kernels 100 times
Precision: double
Array size: 2147.5 MB (=2.1 GB)
Total size: 6442.5 MB (=6.4 GB)
Using alpaka device Tesla V100-SXM2-32GB
Function    MBytes/sec  Min (sec)   Max         Average     
Copy        794093.030  0.00541     0.00542     0.00541     
Mul         800666.506  0.00536     0.00537     0.00537     
Add         819746.406  0.00786     0.00800     0.00798     
Triad       819874.513  0.00786     0.00803     0.00800     
Dot         832608.915  0.00516     0.00520     0.00518   
```
So, at least #1933 should be solved with this.

File: include/alpaka/mem/buf/BufUniformCudaHipRt.hpp [hunk 2]
```diff
@@ -173,9 +174,20 @@ namespace alpaka
         {
             ALPAKA_FN_HOST static auto getPitchBytes(BufUniformCudaHipRt<TApi, TElem, TDim, TIdx> const& buf) -> TIdx
             {
-                return buf.m_pitchBytes; // TODO(bgruber): is this even correct? This reports the pitch for the TDim -
-                                         // 1 dimension, but CUDA's pitch is always the row pitch, independently of the
-                                         // buffer's dimensions.
+                constexpr auto idx = static_cast<TIdx>(DimInt<TDim::value - 1u>::value);
```
Comment (bernhardmgruber) [inline include/alpaka/mem/buf/BufUniformCudaHipRt.hpp]:
```suggestion
                constexpr auto idx = static_cast<TIdx>(TDim::value - 1u);
```

File: include/alpaka/mem/buf/BufUniformCudaHipRt.hpp [hunk 3]
```diff
@@ -173,9 +174,20 @@ namespace alpaka
...
+                constexpr auto bufDim = Dim<BufUniformCudaHipRt<TApi, TElem, TDim, TIdx>>::value;
```
Comment (bernhardmgruber) [inline include/alpaka/mem/buf/BufUniformCudaHipRt.hpp]: Isn't this just:
```suggestion
                constexpr auto bufDim = TDim::value;
```

File: include/alpaka/mem/buf/BufUniformCudaHipRt.hpp (hunk 1 above)
Comment (j-stephan) [reply include/alpaka/mem/buf/BufUniformCudaHipRt.hpp]: Huh, I was sure I deleted this. This shouldn't be here.

Comment (bernhardmgruber) [reply include/alpaka/mem/buf/BufUniformCudaHipRt.hpp]: Interesting. I made that comment a few days ago and it got flushed when I reviewed today, although the line is no longer present in the current changeset :D Well, forget about it :)

**Review by bernhardmgruber — APPROVED** [review]

**Review by fwyzard — COMMENTED** [review]
can you give us a couple of days to check the impact of this PR on the pixeltrack performance, before merging it ?

**Comment by j-stephan** [comment]
Sure! I'll convert it back to a draft until you are done.

**Comment by bernhardmgruber** [comment]
The proposed changes fix issue #1933, great work!

**Comment by fwyzard** [comment]
Sorry for the delay, I finally managed to check this, it looks good on `pixeltrack-standalone`.

**Review by fwyzard — APPROVED** [review]
