### PR TITLE
 Fix OpenMP 5.1 atomics

### LINKED ISSUE #2170: OpenMP backend fails to compile with clang-17
When compiling the unit tests with clang-17, enabling the `ACC_CPU_B_SEQ_T_OMP2` backend, the following failure is reported:
```
/home/bgruber/dev/alpaka/include/alpaka/atomic/AtomicOmpBuiltIn.hpp:190:50: error: the statement for 'atomic compare capture' must be a compound statement of form '{v = x; cond-up-stmt}', ''{cond-up-stmt v = x;}', '{if(x == e) {x = d;} else {v = x;}}', '{r = x == e; if(r) {x = d;}}', or '{r = x == e; if(r) {x = d;} else {v = x;}}', where 'cond-update-stmt' can have one of the following forms: 'if(expr ordop x) {x = expr;}', 'if(x ordop expr) {x = expr;}', 'if(x == e) {x = d;}', or 'if(e == x) {x = d;}' where 'x', 'r', and 'v' are lvalue expressions with scalar type, 'expr', 'e', and 'd' are expressions with scalar type, and 'ordop' is one of '<' or '>'.
  190 |                     ref = (ref <= value) ? ref : value;
      |                                                  ^~~~~
```

### PR DESCRIPTION
**Pull request by bernhardmgruber**
* Workaround clang not recognizing ternay expression
    * Implement atomicInc/atomicDec via omp critical

Fixes: #2170

### CODE REVIEW

**Comment by bernhardmgruber** [comment]
Interstingly, also GCC 13.2 does not compile alpaka's implementation. The following code:
```c++
int atomicInc(int* addr, int value) {
    int old;
    auto& ref = *addr;
    #pragma omp atomic capture compare
    {
        old = ref;
        ref = value < ref ? 0 : ref + 1;
    }
    return old;
}
````
Errors with GCC:
```
<source>: In function 'int atomicInc(int*, int)':
<source>:8:37: error: invalid form of '#pragma omp atomic compare' before '+' token
    8 |         ref = value < ref ? 0 : ref + 1;
      |                                     ^
```
See: https://godbolt.org/z/8r37ev7jE

File: include/alpaka/atomic/AtomicOmpBuiltIn.hpp [hunk 1]
```diff
@@ -217,21 +219,12 @@ namespace alpaka
         {
             ALPAKA_FN_HOST static auto atomicOp(AtomicOmpBuiltIn const&, T* const addr, T const& value) -> T
             {
+                // TODO(bgruber): atomic increment with wrap around is not implementable in OpenMP 5.1
```
Comment (j-stephan) [inline include/alpaka/atomic/AtomicOmpBuiltIn.hpp:222]: I feel that this should be documented somewhere... for users I mean.

**Review by j-stephan — APPROVED** [review]

File: include/alpaka/atomic/AtomicOmpBuiltIn.hpp (hunk 1 above)
Comment (bernhardmgruber) [reply include/alpaka/atomic/AtomicOmpBuiltIn.hpp:222]: For alpaka users or OpenMP users? Do you want me to add a documentation comment in alpaka's source?

Comment (j-stephan) [reply include/alpaka/atomic/AtomicOmpBuiltIn.hpp:222]: For alpaka users. Does CUDA's atomicInc wrap around? If so, this might lead to unexpected results if a user utilizes both the OpenMP and the CUDA back-end.

Comment (bernhardmgruber) [reply include/alpaka/atomic/AtomicOmpBuiltIn.hpp:222]: Yes, CUDA's `atomicInc` wraps around. The OpenMP implementation does the same. It is functionally equivalent. It just uses a lock over an atomic, because we cannot implement it with an atomic.

Comment (j-stephan) [reply include/alpaka/atomic/AtomicOmpBuiltIn.hpp:222]: Ah, I see. Then the TODO is fine.

Comment (bernhardmgruber) [reply include/alpaka/atomic/AtomicOmpBuiltIn.hpp:222]: ok!
