### PR TITLE
move the `Complex` class to `internal` namespace

### LINKED ISSUE #2285: alpaka::sin(alpaka::Complex) produces 'cudaErrorIllegalAddress': 'an illegal memory access was encountered'!
Using alpaka trigonometric functions with alpaka::Complex argument inside a cuda accelerated kernel, produces a weird crash.
Happens on both `1.1.0` and `develop`.

call stack of cuda-gdb
```
#0  0x0000000000000010 in ?? ()
#1  0x00007fffbd25aaf0 in alpaka::sin<float> (x=...) at /home/ich/playground/alpaka_playground/alpaka/include/alpaka/math/Complex.hpp:536
#2  0x00007fffbd258f30 in Kernel::operator()<alpaka::AccGpuUniformCudaHipRt<alpaka::ApiCudaRt, std::integral_constant<unsigned long, 1ul>, int> > (this=0x7fffdbfffc6c, acc=..., f=0x7fffb3600000) at /home/ich/playground/alpaka_playground/src/main.cpp:19
#3  0x00007fffbd257db0 in alpaka::detail::gpuKernel<Kernel, alpaka::ApiCudaRt, alpaka::AccGpuUniformCudaHipRt<alpaka::ApiCudaRt, std::integral_constant<unsigned long, 1ul>, int>, std::integral_constant<unsigned long, 1ul>, int, float*><<<(1,1,1),(1024,1,1)>>> (threadElemExtent=..., 
    kernelFnObj=..., args=0x7fffb3600000)
    at /home/ich/playground/alpaka_playground/alpaka/include/alpaka/kernel/TaskKernelGpuUniformCudaHipRt.hpp:79
```
from another project we can see that alpaka::cos seems to call a function that is completely out of scope. weird.
```
#0  0x0000000000000010 in RAYX::findCollisionInElementCoords (r=..., surface=..., cutout=..., isTriangul=<unavailable>)
    at /home/ich/projects/rayx/Intern/rayx-core/src/Shader/Collision.cpp:394
#1  0x00007fffbd36a110 in alpaka::cos<double> (x=...) at /home/ich/projects/rayx/Extern/alpaka/include/alpaka/math/Complex.hpp:445   -G "Ninja" $HOME/projects/rayx
```

nvcc version
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0
```

cmake command:
```
cmake \
    -DCMAKE_BUILD_TYPE=Debug \
    -Dalpaka_ACC_GPU_CUDA_ENABLE=ON \
    -DCMAKE_CXX_COMPILER=g++-12 \
    -DCMAKE_CUDA_ARCHITECTURES=52 \
    -G "Ninja" ..
```

I see that alpaka uses the std implementation of those functions. When i try to use them in a cuda-only project, then i get an error because these function are not annotated with `__device__`.
```
main.cu(15): error: calling a __host__ function("std::complex<T1>   ::std::sin<float> (const     ::std::complex<T1>  &)") from a __global__ function("kernel") is not allowed
main.cu(15): error: identifier "std::sin<float> " is undefined in device code
```

Am I doing something wrong here or do you maybe have a hint for us? We really would appreciate an implementation of complex numbers within our project. Maybe a specialization of the alpaka::math functions for complex numbers could be using funcitonallity from cuComplex.h instead?

### PR DESCRIPTION
**Pull request by AuroraPerego**
should fix #2285 

The example provided in the issue does not compile now, it says that there is no `sin` function in the `alpaka` namespace.

I can squash the commits in one if you want, I've kept them separate to show the real change which is quite small.

### CODE REVIEW

File: include/alpaka/math/Complex.hpp [hunk 1]
```diff
@@ -14,560 +14,569 @@
...
+        //! All methods besides operators << and >> are host-device.
+        //! It does not provide non-member functions of std::complex besides the operators.
+        //! Those are provided the same way as alpaka math functions for real numbers.
+        //!
+        //! Note that unlike most of alpaka, this is a concrete type template, and not merely a concept.
+        //!
+        //! Naming and order of the methods match https://en.cppreference.com/w/cpp/numeric/complex in C++17.
+        //! Implementation chose to not extend it e.g. by adding constexpr to some places that would get it in C++20.
+        //! The motivation is that with internal conversion to std::complex<T> for CPU backends, it would define the
+        //! common interface for genetic code anyways. So it is more clear to have alpaka's interface exactly matching
```
Comment (fwyzard) [inline include/alpaka/math/Complex.hpp]:
```suggestion
        //! common interface for generic code anyways. So it is more clear to have alpaka's interface exactly matching
```
?

Comment (AuroraPerego) [reply include/alpaka/math/Complex.hpp]: fixed :)

**Review by fwyzard — APPROVED** [review]

File: include/alpaka/math/Complex.hpp [hunk 2]
```diff
@@ -14,560 +14,569 @@
...
+        constexpr ALPAKA_FN_HOST_ACC Complex<T> tanh(Complex<T> const& x)
+        {
+            return std::tanh(std::complex<T>(x));
+        }
 
-    //! @}
+        //! @}
+    } // namespace internal
 
+    using internal::Complex;
```
Comment (mehmetyusufoglu) [inline include/alpaka/math/Complex.hpp:581]: [Question, non-blocking] @AuroraPerego  is this the alias which makes the ADL possible?
